# -*- coding: utf-8 -*-
"""grouppro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-b9HRNAsw7ijw9SD-Rdo3KNggbF3wRYG

# **Bigfoot** **Project**
April 4, 2021

Qiming Li

Bigfoot, also known as Sasquatch, is an ape-like creature purported to inhabit the forests of North America. This project will conduct a descriptive statistics analysis of the data taking a look at the data set collected from observers by the Bigfoot Field Researchers Organization (BFRO) and provide insightful visualizations indicating the appearance of Bigfoot, or the credibility of evidence of Bigfoot. The data set contains 4747 records of Bigfoot sightings in the US. Variables include text of the report, latitude/longitude of the sighting, sighting date, number (a report number), classification (see BFRO link), and a variety of weather conditions (added later for some reports based on weather records). Other supporting data sets we may need are county information and geographic data of the US. To better handle the data, we need to do the data cleansing to deal with missing data points. Questions we aim to answer include:


*   What exact characteristics of a US county are associated with Bigfoot sightings?

*   What trends are there in the number of reported Bigfoot sightings over time?


*   Is there a common narrative or a common physical description of Bigfoot? 

The rest of the report will contain a brief discussion of methodology, visualizations and interpretation, and conclusion of findings.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.colors as colors
import wordcloud
import re
import geopandas as gpd
from shapely.geometry import Point
from shapely.geometry import LineString
from shapely.ops import split
from shapely.affinity import translate

"""Handling missing data was the first step to do the analysis of bigfoot records in contiguous US states, but US county geospatial data we got contained non-contiguous ones. We dropped Alaska, Hawaii, and US Territories (non-contiguous states) points in terms of their State FIPS Codes which are used to identify US geographical units, and finally saved 48 contiguous states geospatial into a new data file. There are lots of Bigfoot sightings that did not take place in contiguous states either. We dropped missing location rows of bigfoot observation and then went through all rows in the new Bigfoot data set in order to eliminate sightings outside the contiguous US states. It is easy to check whether a sighting point is contained in each county polygon since we have its position coordinates (latitude and longitude). We also counted the number of Bigfoot sightings in each county in this way and stored the results in a new column of county data set to do a map plot.

In order to find the trend of Bigfoot sightings over years, we selected the date column which is a string type in Bigfoot data set and extracted the last two characters representing year without century in each raw. We converted them into integer data type, used the formula below to calculated years with century and stored them in a new list. It is easy to do a scatter plot since we could count Bigfoot sightings happened with the same year.

                        (year + 80) % 100 + 1920

At the end, we wanted to explore what the relationship between economic/population characteristics of a US county and the number of Bigfoot sightings is, so we incorporated economic and population variables in county-level data sets with Bigfoot sightings in each county. As for common physical description of Bigfoot, we downloaded a very common stopwords text file online and added other stopwords from Bigfoot observation to omit a list of words we thought were unrelated with Bigfoot description. High-frequency words used to describe Bigfoot were well illustrated in  the wordcloud image.

"""

us = gpd.read_file('cb_2018_us_county_5m.shp')
index = np.array(us.STATEFP).astype(np.int)
new_us = us.iloc[(index < 60) & (index != 2) & (index != 15)]
new_us.to_pickle('counties_clean.pkl', protocol = 4)

#delete rows without coordinates info or not in ontiguous US
data = pd.read_csv('bigfoot.csv').iloc[:, 2:6].dropna(axis=0, subset=["latitude", "longitude"])
index = np.zeros(data.shape[0])
for i in range(len(data)):
    p = Point(data.longitude.iloc[i], data.latitude.iloc[i])
    for poly in new_us.geometry:
        if poly.contains(p):
            index[i] = 1
            break
data = data[index.astype(np.bool)]
data.to_pickle('bigfoot_geo.pkl', protocol = 4)


bigfoot_geo = pd.read_pickle('bigfoot_geo.pkl')
counties = pd.read_pickle('counties_clean.pkl')
counties["totalNum"] = 0
indexCounty = 0
for poly in counties.geometry:
    for j in range(len(bigfoot_geo)):
        p = Point(bigfoot_geo.longitude.iloc[j], bigfoot_geo.latitude.iloc[j])
        if poly.contains(p):
            counties["totalNum"].iloc[indexCounty] += 1
    indexCounty += 1
counties.to_pickle('counties_totalNum.pkl', protocol = 4)

bigfoot_geo = pd.read_pickle('bigfoot_geo.pkl')
counties = pd.read_pickle('counties_clean.pkl')

fig, ax = plt.subplots(figsize=(20,20))
counties.plot(ax=ax, color='darkseagreen', edgecolor='ghostwhite')
bigfoot_geo = gpd.GeoDataFrame(bigfoot_geo, crs="EPSG:4326",geometry=gpd.points_from_xy(bigfoot_geo.longitude, bigfoot_geo.latitude))
bigfoot_geo.plot(ax=ax, color="black", markersize=200 , marker='.', alpha=.9)
ax.set_title("\nLocations of Bigfoot Sightings in Contiguous US States\n", fontsize=30)
ax.axis('off')

"""The above graph indicates the locations of Bigfoot sightings in contiguous US states. As illustrated in the picture, Bigfoot sightings are heavily distributed among those states such as Washington, Oregon, California, Florida, Mississippi, Missouri and so on. They all have one thing in common which is that almost all bigfoot sightings are found in heavily forested areas. There are almost no traces of Bigfoot in the plains or deserts area like State of Nevada, Oklahoma, Arkansas, or Nebraska.

"""

counties_totalNum = pd.read_pickle('counties_totalNum.pkl')

fig, ax = plt.subplots(figsize=(20,20))
counties_totalNum.plot(ax=ax, edgecolor='lightcoral', column='totalNum',cmap="Reds",norm=colors.LogNorm())
sm = plt.cm.ScalarMappable(cmap='Reds',norm=plt.Normalize(vmin=min(counties_totalNum.totalNum),vmax=max(counties_totalNum.totalNum)))
plt.colorbar(sm, fraction = 0.015)
ax.set_title("\nNumber of Bigfoot Sightings in Contiguous US Counties\n", fontsize=30)
ax.axis('off')

"""The Bigfoot sightings in US Counties also proved our prior finding that Bigfoots are mostly reported in the forest area. There are almost no Bigfoot sightings in the counties in the middle part of the map. We have also found that the number of Bigfoot sightings is also directly linked to the population of the area. For instance, state of Montana has a very large land of area and it also has a large forest area. However, it has only a few of reported sightings of Bigfoot which is most likely resulted by the small population of the state.

"""

datasize = len(bigfoot_geo)
datayear = np.zeros(datasize)
for i in range(datasize):
    datayear[i] = int(bigfoot_geo.date.iloc[i][-2:])
datayear = (datayear + 80) % 100 + 1920
yearline = np.arange(1921, 2019)
yeartimes = np.zeros(len(yearline))
for i in range(datasize):
    yeartimes[datayear[i] == yearline] += 1
plt.figure(figsize = (10,6))
plt.plot(yearline, yeartimes)
plt.title('Number of Bigfoot Sightings Over Years\n', fontsize=20)
plt.xlabel("Year", fontsize=14)
plt.ylabel("Bigfoot Sightings", fontsize=14)
plt.tick_params(axis='both', labelsize=10)
plt.show()

"""The first bigfoot sighting happened in 1920s. The sightings of Bigfoot started increasing rapidly in 2000, and there has been a significant downward trend in recent years.

"""

maga = counties_totalNum[['COUNTYNS', 'totalNum']].to_numpy()
us['bigfoot'] = 0
for i in range(len(maga)):
    us['bigfoot'].loc[np.array(us.COUNTYNS) == maga[i, 0]] =  maga[i, 1]
trump = pd.read_csv('county_data.csv').dropna(axis=0, subset=['county'])
trump['bigfoot'] = 0
for i in range(us.NAME.shape[0]):
    trump['bigfoot'].loc[np.array(trump.county) == us.NAME.iloc[i]] = us.bigfoot.iloc[i]

ipc = np.zeros(trump.income_per_cap.shape[0])
for i in range(trump.income_per_cap.shape[0]):
    ipc[i] = int(re.sub("\D", "", trump.income_per_cap.iloc[i]))
bf = np.array(trump.bigfoot)
plt.figure(figsize = (10,6))
plt.scatter(ipc, bf, s=10)
plt.title('Bigfoot Sightings - Income per Cap\n', fontsize=20)
plt.tick_params(axis='both', labelsize=10)
plt.show()

"""In this section, we compared the Bigfoot sightings with the county’s income per capita. There is a heavy distribution of bigfoot sightings between $10,000 to $30,000 income per capita by county. The average income per capita in the U.S is proximately $50,000 which is much higher than the previous number. The hypothesis of low per capita income may be due to the low level of development in this area and more undeveloped land which are forests. """

popu = np.zeros(trump.population.shape[0])
for i in range(trump.population.shape[0]):
    popu[i] = int(re.sub("\D", "", trump.population.iloc[i]))
bf = np.array(trump.bigfoot)
plt.figure(figsize = (10,6))
plt.scatter(popu, bf, s=10)
plt.title('Bigfoot Sightings - Population\n', fontsize=20)
plt.tick_params(axis='both', labelsize=10)
plt.show()

"""Next, we compared the Bigfoot sightings with the county’s population to further verify our hypothesis. As the graph shown: Bigfoot are often being sighted in the area has low population.  """

data = pd.read_csv('bigfoot.csv')
x = " ".join(data.observed.dropna( ))
lines = []
with open('stopwords.txt', 'r') as file_to_read:
    while True:
        line = file_to_read.readline()
        if not line:
            break
        line = line.strip('\n')
        if line != '':
            lines.append(line)
            
y = lines + ['heard', 'time', 'road', 'sound', 'tree','looked','house','wood','car','bigfoot','friend','direction','son',
             'left','night', 'car','creature','yard','feet','walking','told','track','trail','dog','started','friend',
             'trees', 'head','minute','woods','animal','dog','told','day','trees','mile','decided','bear','hear','rock',
             'yards','tracks','noise','hill','walked','deer','light','deer','hill','stopped','minutes','hour','moving',
             'morning','front','truck','coming','noticed','stood','standing','brother','walk','people','sounds','sounded',
             'window','top','wife','close','tent','happened','hunting','call','running','dad','moved','sighting','remember',
             'incident','rock','time','spot','figure','driving','distance','step','half','time','lot','ground','husband']

cloud = wordcloud.WordCloud(max_words = 20, stopwords = y).generate(x)
plt.subplots(figsize=(15,15))
plt.imshow(cloud, interpolation="bilinear")
plt.axis('off')

"""From the word cloud result, we can see that people often use words “eye”, “leg”, “tall”, and “human” to describe the appearance of Bigfoot. They usually spot Bigfoot near “lake”, “river”, “creek” and “camp”. These statements further validate our previous conclusions that most of Bigfoot was found near the forest.

Here are the key takeaways  from our analysis. The locations of Bigfoot sightings in contiguous US states are heavily distributed among those states having large areas of forest such as Washington, Oregon, California, Florida, Mississippi, Missouri and so on. The number of Bigfoot sightings is also directly linked to the population of that area.
The first bigfoot sighting happened in the 1920s. The reported sightings of Bigfoot started increasing rapidly in 2000. Afterward, there has been a significant downward trend in recent years. From the data set, we found there are some common words for observers describing their discovered bigfoot sightings, like camp, lake, river, creek, running, and dark. These words illustrate the location of where people see Bigfoot and how they look like.
"""